services:
  db:
    image: postgres:latest
    build:
      context: .    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./Postgres/volumes:/var/lib/postgresql/data
